# Generated by Django 3.0.2 on 2020-01-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='giver',
            field=models.IntegerField(choices=[(1, 'Prapor'), (2, 'Therapist'), (3, 'Skier'), (4, 'Peacekeeper'), (5, 'Mechanic'), (6, 'Ragman'), (7, 'Jaeger'), (8, 'Fence')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='map',
            field=models.IntegerField(choices=[(1, 'Customs'), (2, 'Factory'), (3, 'Woods'), (4, 'Interchange'), (5, 'Reserve'), (6, 'Shoreline'), (7, 'Labs')], default=1),
        ),
    ]
